{
  This file is part of Gilbertsoft SynWebBroker (GSSWB).

  Copyright (C) 2018-2019 Simon Gilli
    Gilbertsoft | https://delphi.gilbertsoft.org

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program.  If not, see <https://www.gnu.org/licenses/>.
}
    '<!DOCTYPE html>'#13#10 +
    '<html>'#13#10 +
    '<head>'#13#10 +
    '    <title>%s</title>'#13#10 +
    '    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />'#13#10 +
    '    <meta name="robots" content="noindex, follow" />'#13#10 +
    '    <style type="text/css"><!--'#13#10 +
    '    body {'#13#10 +
    '        color: #444444;'#13#10 +
    '        background-color: #EEEEEE;'#13#10 +
    '        font-family: ''Trebuchet MS'', sans-serif;'#13#10 +
    '        font-size: 80%%;'#13#10 +
    '    }'#13#10 +
    '    h1 {}'#13#10 +
    '    h2 { font-size: 1.2em; }'#13#10 +
    '    #page{'#13#10 +
    '        background-color: #FFFFFF;'#13#10 +
    '        width: 60%%;'#13#10 +
    '        margin: 24px auto;'#13#10 +
    '        padding: 12px;'#13#10 +
    '    }'#13#10 +
    '    #header {'#13#10 +
    '        padding: 6px ;'#13#10 +
    '        text-align: center;'#13#10 +
    '    }'#13#10 +
    '    .status3xx { background-color: #475076; color: #FFFFFF; }'#13#10 +
    '    .status4xx { background-color: #C55042; color: #FFFFFF; }'#13#10 +
    '    .status5xx { background-color: #F2E81A; color: #000000; }'#13#10 +
    '    #content {'#13#10 +
    '        padding: 4px 0 24px 0;'#13#10 +
    '    }'#13#10 +
    '    #footer {'#13#10 +
    '        color: #666666;'#13#10 +
    '        background: #f9f9f9;'#13#10 +
    '        padding: 10px 20px;'#13#10 +
    '        border-top: 5px #efefef solid;'#13#10 +
    '        font-size: 0.8em;'#13#10 +
    '        text-align: center;'#13#10 +
    '    }'#13#10 +
    '    #footer a {'#13#10 +
    '        color: #999999;'#13#10 +
    '    }'#13#10 +
    '    --></style>'#13#10 +
    '</head>'#13#10 +
    '<body>'#13#10 +
    '    <div id="page">'#13#10 +
    '        <div id="header" class="status%dxx">'#13#10 +
    '            <h1>ERROR %d - %s</h1>'#13#10 +
    '        </div>'#13#10 +
    '        <div id="content">'#13#10 +
    '            <h2>Reason:</h2>'#13#10 +
    '            <p>%s</p>'#13#10 +
    '        </div>'#13#10 +
    '        <div id="footer">'#13#10 +
    '            <p>Powered by <a href="https://github.com/gilbertsoft/delphi-SynWebBroker">SynWebBroker</a> by <a href="https://www.gilbertsoft.org/">Gilbertsoft</a> and <a href="http://mormot.net/">mORMot</a></p>'#13#10 +
    '        </div>'#13#10 +
    '    </div>'#13#10 +
    '</body>'#13#10 +
    '</html>'#13#10